// Base de questions. Format : [niveau 1-5, question, BONNE réponse, mauvaise, mauvaise, mauvaise]
// La bonne réponse est toujours en 2e position ici ; le jeu mélange les choix à l'affichage.
const QUESTIONS = {
  foot: [
    [1, "Combien de joueurs par équipe sur le terrain au football ?", "11", "10", "12", "9"],
    [1, "Quel pays a remporté la Coupe du monde 2018 ?", "France", "Croatie", "Belgique", "Brésil"],
    [1, "Quel pays a remporté la Coupe du monde 2022 ?", "Argentine", "France", "Maroc", "Croatie"],
    [1, "Combien de temps dure un match (temps réglementaire) ?", "90 minutes", "80 minutes", "100 minutes", "120 minutes"],
    [1, "Quel carton signifie l'exclusion d'un joueur ?", "Rouge", "Jaune", "Blanc", "Vert"],
    [1, "Quel club joue au Parc des Princes ?", "Paris Saint-Germain", "Olympique de Marseille", "Paris FC", "Olympique lyonnais"],
    [1, "Dans quel stade joue l'Olympique de Marseille ?", "Le Vélodrome", "Geoffroy-Guichard", "La Beaujoire", "Le Stade de France"],
    [1, "Quel joueur est surnommé « CR7 » ?", "Cristiano Ronaldo", "Ronaldinho", "Ronaldo (le Brésilien)", "Cristian Romero"],
    [1, "Qui a le droit de toucher le ballon avec les mains dans sa surface ?", "Le gardien", "Le capitaine", "Le libéro", "Personne"],
    [1, "Le « Clasico » espagnol oppose le FC Barcelone à…", "Real Madrid", "Atlético Madrid", "FC Séville", "Valence"],
    [1, "Le « Classique » français oppose le PSG à…", "Marseille", "Lyon", "Saint-Étienne", "Lens"],
    [1, "Quel pays a accueilli la Coupe du monde 2022 ?", "Qatar", "Russie", "Arabie saoudite", "Émirats arabes unis"],
    [1, "Que signifie le sigle VAR ?", "Assistance vidéo à l'arbitrage", "Vitesse au ralenti", "Validation automatique des règles", "Vue arrière du ralenti"],
    [1, "De quel pays est originaire Zlatan Ibrahimović ?", "Suède", "Norvège", "Danemark", "Croatie"],
    [1, "Comment appelle-t-on trois buts marqués par le même joueur dans un match ?", "Un triplé", "Un doublé", "Une manita", "Un grand chelem"],
    [1, "Le stade de Wembley se trouve à…", "Londres", "Manchester", "Liverpool", "Birmingham"],
    [1, "Quelle sélection est surnommée « les Oranje » ?", "Pays-Bas", "Côte d'Ivoire", "Irlande", "Belgique"],

    [2, "Qui était le sélectionneur de la France championne du monde en 2018 ?", "Didier Deschamps", "Zinédine Zidane", "Laurent Blanc", "Raymond Domenech"],
    [2, "Quel club a remporté le plus de Ligues des champions ?", "Real Madrid", "AC Milan", "Bayern Munich", "Liverpool"],
    [2, "Quel joueur a remporté le plus de Ballons d'or ?", "Lionel Messi", "Cristiano Ronaldo", "Michel Platini", "Johan Cruyff"],
    [2, "Qui a marqué deux buts de la tête en finale de la Coupe du monde 1998 ?", "Zinédine Zidane", "Emmanuel Petit", "Lilian Thuram", "Thierry Henry"],
    [2, "Quel a été le score de la finale France – Brésil en 1998 ?", "3-0", "2-0", "3-1", "1-0"],
    [2, "Sur quel joueur Zidane a-t-il donné son coup de tête en finale 2006 ?", "Marco Materazzi", "Fabio Cannavaro", "Gennaro Gattuso", "Gianluigi Buffon"],
    [2, "Quel club est surnommé « les Verts » ?", "AS Saint-Étienne", "FC Nantes", "Racing Club de Lens", "OGC Nice"],
    [2, "Dans quelle ville joue la Juventus ?", "Turin", "Milan", "Rome", "Naples"],
    [2, "Quel club anglais est surnommé « les Gunners » ?", "Arsenal", "Chelsea", "Tottenham", "West Ham"],
    [2, "Quel club anglais est surnommé « les Red Devils » ?", "Manchester United", "Liverpool", "Manchester City", "Nottingham Forest"],
    [2, "Quel pays a remporté l'Euro 2016, en battant la France en finale ?", "Portugal", "Allemagne", "Espagne", "Italie"],
    [2, "Quel pays a remporté l'Euro 2024 ?", "Espagne", "Angleterre", "France", "Allemagne"],
    [2, "Qui a gagné le Ballon d'or 2022 ?", "Karim Benzema", "Lionel Messi", "Robert Lewandowski", "Kylian Mbappé"],
    [2, "Combien de remplacements une équipe peut-elle faire en match officiel (hors prolongation) ?", "5", "3", "4", "6"],
    [2, "Qui a marqué un triplé en finale de la Coupe du monde 2022 ?", "Kylian Mbappé", "Lionel Messi", "Olivier Giroud", "Antoine Griezmann"],
    [2, "Dans quel club Kylian Mbappé a-t-il débuté en professionnel ?", "AS Monaco", "Paris Saint-Germain", "Real Madrid", "Lille OSC"],
    [2, "Avec quel club Zidane a-t-il gagné trois Ligues des champions de suite comme entraîneur ?", "Real Madrid", "Juventus", "Bordeaux", "Bayern Munich"],
    [2, "Quel club a remporté la Ligue des champions 2025 ?", "Paris Saint-Germain", "Inter Milan", "Real Madrid", "Arsenal"],
    [2, "Quel est le stade du Bayern Munich ?", "Allianz Arena", "Signal Iduna Park", "Olympiastadion", "Veltins-Arena"],
    [2, "Comment s'appelle le stade de Liverpool ?", "Anfield", "Old Trafford", "Goodison Park", "Stamford Bridge"],
    [2, "Quel joueur est surnommé « La Pulga » ?", "Lionel Messi", "Neymar", "Sergio Agüero", "Paulo Dybala"],
    [2, "Quel pays a remporté la Coupe du monde 2010 ?", "Espagne", "Pays-Bas", "Allemagne", "Italie"],
    [2, "Quelle sélection est surnommée « la Squadra Azzurra » ?", "Italie", "Uruguay", "Grèce", "Argentine"],
    [2, "Quelle sélection est surnommée « les Diables rouges » ?", "Belgique", "Espagne", "Suisse", "Chili"],
    [2, "Dans quel club Éric Cantona est-il devenu une légende en Angleterre ?", "Manchester United", "Leeds United", "Arsenal", "Liverpool"],
    [2, "Combien durent les prolongations ?", "2 × 15 minutes", "2 × 10 minutes", "1 × 20 minutes", "2 × 20 minutes"],
    [2, "Dans quel club évoluait Neymar avant son arrivée au PSG en 2017 ?", "FC Barcelone", "Santos", "Real Madrid", "Chelsea"],
    [2, "De quel pays est originaire Didier Drogba ?", "Côte d'Ivoire", "Cameroun", "Sénégal", "Ghana"],

    [3, "Contre quel club l'OM a-t-il gagné la finale de la Ligue des champions 1993 ?", "AC Milan", "Juventus", "FC Barcelone", "Ajax Amsterdam"],
    [3, "Qui a marqué le but en or de la France en finale de l'Euro 2000 ?", "David Trezeguet", "Sylvain Wiltord", "Thierry Henry", "Robert Pirès"],
    [3, "Quel entraîneur a mené le FC Barcelone au sextuplé en 2009 ?", "Pep Guardiola", "Frank Rijkaard", "Luis Enrique", "Johan Cruyff"],
    [3, "Contre quel pays Maradona a-t-il marqué la « main de Dieu » en 1986 ?", "Angleterre", "Allemagne de l'Ouest", "Belgique", "Italie"],
    [3, "Quel pays a remporté la toute première Coupe du monde, en 1930 ?", "Uruguay", "Argentine", "Brésil", "Italie"],
    [3, "Qui a remporté le Ballon d'or 1998 ?", "Zinédine Zidane", "Ronaldo", "Davor Šuker", "Dennis Bergkamp"],
    [3, "Qui a remporté le Ballon d'or 2018 ?", "Luka Modrić", "Cristiano Ronaldo", "Antoine Griezmann", "Kylian Mbappé"],
    [3, "Quel Français a remporté le Ballon d'or 2025 ?", "Ousmane Dembélé", "Kylian Mbappé", "Michael Olise", "William Saliba"],
    [3, "Combien de titres de champion de France consécutifs Lyon a-t-il gagnés de 2002 à 2008 ?", "7", "5", "6", "8"],
    [3, "Quel est le meilleur buteur de l'histoire de la Ligue des champions ?", "Cristiano Ronaldo", "Lionel Messi", "Robert Lewandowski", "Karim Benzema"],
    [3, "Quel est le meilleur buteur de l'histoire d'Arsenal ?", "Thierry Henry", "Ian Wright", "Dennis Bergkamp", "Robin van Persie"],
    [3, "Dans quel club brésilien Pelé a-t-il joué la majeure partie de sa carrière ?", "Santos", "Flamengo", "Corinthians", "Palmeiras"],
    [3, "Quelle saison Leicester a-t-il été sacré champion d'Angleterre, à la surprise générale ?", "2015-2016", "2013-2014", "2016-2017", "2018-2019"],
    [3, "Quel pays a remporté l'Euro 2004 à la surprise générale ?", "Grèce", "Portugal", "République tchèque", "Danemark"],
    [3, "Quel joueur a marqué le but de la victoire en finale de la Coupe du monde 2010 ?", "Andrés Iniesta", "David Villa", "Xavi", "Fernando Torres"],
    [3, "Quel pays a organisé et remporté la Coupe du monde 1966 ?", "Angleterre", "Allemagne de l'Ouest", "Italie", "Brésil"],
    [3, "Quel club est surnommé « les Canaris » ?", "FC Nantes", "FC Sochaux", "Stade brestois", "FC Lorient"],
    [3, "Quel club est surnommé « les Sang et Or » ?", "RC Lens", "Stade rennais", "Toulouse FC", "FC Metz"],
    [3, "En 2005, Liverpool gagne la Ligue des champions après avoir été mené 3-0 à la mi-temps. Contre qui ?", "AC Milan", "Juventus", "Chelsea", "FC Barcelone"],
    [3, "Avec quel club José Mourinho a-t-il gagné sa première Ligue des champions (2004) ?", "FC Porto", "Chelsea", "Inter Milan", "Benfica"],
    [3, "Quel joueur brésilien était surnommé « Il Fenomeno » ?", "Ronaldo", "Romário", "Rivaldo", "Kaká"],
    [3, "Quel pays est devenu en 2022 le premier pays africain demi-finaliste d'une Coupe du monde ?", "Maroc", "Sénégal", "Cameroun", "Ghana"],
    [3, "Combien d'équipes participent à la Coupe du monde 2026 ?", "48", "32", "40", "64"],
    [3, "Combien de clubs composent la Ligue 1 depuis la saison 2023-2024 ?", "18", "20", "16", "19"],
    [3, "Quelle sélection est surnommée « les Lions de la Teranga » ?", "Sénégal", "Cameroun", "Maroc", "Mali"],
    [3, "Le hors-jeu ne peut pas être sifflé directement sur…", "Une rentrée de touche", "Un coup franc indirect", "Une passe en retrait", "Un centre"],
    [3, "Quel pays a remporté l'Euro 1984, avec un Platini auteur de 9 buts ?", "France", "Espagne", "Allemagne de l'Ouest", "Portugal"],
    [3, "Avec quel club Johan Cruyff a-t-il débuté et gagné trois Coupes des clubs champions ?", "Ajax Amsterdam", "Feyenoord", "PSV Eindhoven", "FC Barcelone"],
    [3, "Quel est le stade de l'Olympique lyonnais ?", "Groupama Stadium", "Stade de Gerland", "Allianz Riviera", "Matmut Atlantique"],
    [3, "Combien de Coupes du monde la France a-t-elle gagnées entre 1930 et 2022 ?", "2", "1", "3", "4"],

    [4, "Qui a remporté le Ballon d'or 1991 ?", "Jean-Pierre Papin", "Lothar Matthäus", "Marco van Basten", "Éric Cantona"],
    [4, "Combien de Ballons d'or Michel Platini a-t-il remportés ?", "3", "2", "4", "1"],
    [4, "Qui a été le premier Français à remporter le Ballon d'or (1958) ?", "Raymond Kopa", "Just Fontaine", "Michel Platini", "Jean-Pierre Papin"],
    [4, "Quel Français détient le record de buts sur une seule Coupe du monde (13 en 1958) ?", "Just Fontaine", "Raymond Kopa", "Michel Platini", "Thierry Henry"],
    [4, "Dans quelle ville s'est jouée la finale de la Coupe du monde 2006 ?", "Berlin", "Munich", "Dortmund", "Hambourg"],
    [4, "Contre quel club Saint-Étienne a-t-il perdu la finale de la Coupe des clubs champions 1976 (les « poteaux carrés ») ?", "Bayern Munich", "Liverpool", "Ajax Amsterdam", "Real Madrid"],
    [4, "Qui a marqué le but de la victoire en finale de la Coupe du monde 2014 ?", "Mario Götze", "Thomas Müller", "Miroslav Klose", "André Schürrle"],
    [4, "Quel est le seul gardien de but à avoir remporté le Ballon d'or ?", "Lev Yachine", "Gianluigi Buffon", "Manuel Neuer", "Dino Zoff"],
    [4, "Quel est le seul joueur africain à avoir remporté le Ballon d'or ?", "George Weah", "Didier Drogba", "Samuel Eto'o", "Roger Milla"],
    [4, "Quelles sont les dimensions officielles d'un but ?", "7,32 m × 2,44 m", "7 m × 2,50 m", "8 m × 2,40 m", "7,50 m × 2,44 m"],
    [4, "Quel a été le score de la « remontada » du Barça contre le PSG en 2017 (match retour) ?", "6-1", "5-1", "4-0", "6-2"],
    [4, "Quel a été le score de la finale de la Ligue des champions 2025 PSG – Inter ?", "5-0", "3-0", "2-1", "4-1"],
    [4, "Quel joueur détient le record de sélections en équipe de France ?", "Hugo Lloris", "Lilian Thuram", "Antoine Griezmann", "Thierry Henry"],
    [4, "Quel club est surnommé « les Dogues » ?", "Lille OSC", "Stade de Reims", "AJ Auxerre", "Montpellier HSC"],
    [4, "Qui a remporté le Ballon d'or 2006 ?", "Fabio Cannavaro", "Gianluigi Buffon", "Thierry Henry", "Ronaldinho"],
    [4, "Contre quel club l'OM a-t-il perdu la finale de la Ligue Europa 2018 ?", "Atlético Madrid", "FC Séville", "Chelsea", "Manchester United"],
    [4, "Pour environ combien d'argent Neymar a-t-il été transféré au PSG en 2017 ?", "222 millions d'euros", "150 millions d'euros", "180 millions d'euros", "300 millions d'euros"],
    [4, "Quel pays a remporté la CAN 2021 (jouée en 2022) ?", "Sénégal", "Égypte", "Cameroun", "Algérie"],
    [4, "Quel pays a remporté la CAN 2019 ?", "Algérie", "Sénégal", "Nigeria", "Tunisie"],
    [4, "Par quel score l'Allemagne a-t-elle battu le Brésil en demi-finale de la Coupe du monde 2014 ?", "7-1", "5-0", "6-1", "4-0"],
    [4, "Quel club a remporté la première Coupe des clubs champions, en 1956 ?", "Real Madrid", "Stade de Reims", "Benfica", "AC Milan"],
    [4, "Quel club français a perdu la première finale de Coupe des clubs champions, en 1956 ?", "Stade de Reims", "OGC Nice", "AS Saint-Étienne", "Racing Club de Paris"],
    [4, "Quel club a remporté le plus de Coupes de France ?", "Paris Saint-Germain", "Olympique de Marseille", "AS Saint-Étienne", "Lille OSC"],
    [4, "Quel joueur italien a été surnommé « Il Divin Codino » ?", "Roberto Baggio", "Paolo Maldini", "Alessandro Del Piero", "Francesco Totti"],
    [4, "Avec quel club Didier Deschamps a-t-il gagné la Ligue des champions 1996 comme joueur ?", "Juventus", "Olympique de Marseille", "Chelsea", "Valence"],

    [5, "Quel joueur a marqué le premier but de l'histoire de la Coupe du monde, en 1930 ?", "Lucien Laurent", "Just Fontaine", "Raymond Kopa", "Juste Brouzes"],
    [5, "Quel est le vrai prénom de Pelé ?", "Edson", "Arantes", "Ronaldo", "José"],
    [5, "En quelle année a été rendu l'arrêt Bosman ?", "1995", "1992", "1998", "2001"],
    [5, "Quel pays a remporté la Coupe du monde 1954 (le « miracle de Berne ») ?", "RFA", "Hongrie", "Uruguay", "Brésil"],
    [5, "Le Danemark a gagné l'Euro 1992 en remplaçant au dernier moment quelle sélection exclue ?", "Yougoslavie", "URSS", "Tchécoslovaquie", "Roumanie"],
    [5, "Quel club français a remporté la Coupe des coupes en 1996 ?", "Paris Saint-Germain", "Olympique de Marseille", "AS Monaco", "Girondins de Bordeaux"],
    [5, "Qui a été la première lauréate du Ballon d'or féminin, en 2018 ?", "Ada Hegerberg", "Megan Rapinoe", "Alexia Putellas", "Amandine Henry"],
    [5, "En quelle année l'UEFA a-t-elle supprimé la règle du but à l'extérieur ?", "2021", "2018", "2019", "2023"],
    [5, "À quelle distance du ballon doit se placer le mur adverse sur un coup franc ?", "9,15 m", "9 m", "10 m", "11 m"],
    [5, "Quel club amateur a atteint la finale de la Coupe de France 2000 ?", "Calais RUFC", "US Quevilly", "Les Herbiers", "Chambly"],
    [5, "Qui a marqué le but de la victoire de l'OM en finale de la Ligue des champions 1993 ?", "Basile Boli", "Rudi Völler", "Alen Bokšić", "Abedi Pelé"],
    [5, "Quel club a remporté le premier championnat de France professionnel, en 1932-1933 ?", "Olympique lillois", "Olympique de Marseille", "FC Sète", "Racing Club de Paris"],
    [5, "Combien de buts Just Fontaine a-t-il marqués lors de la Coupe du monde 1958 ?", "13", "11", "9", "15"],
    [5, "Quel pays a remporté la Coupe du monde 1950 au Maracanã (le « Maracanazo ») ?", "Uruguay", "Brésil", "Suède", "Italie"],
    [5, "Combien de Coupes du monde Pelé a-t-il remportées comme joueur ?", "3", "2", "4", "1"],
    [5, "Quel gardien français détient le record de matchs joués en Ligue 1 ?", "Mickaël Landreau", "Fabien Barthez", "Steve Mandanda", "Hugo Lloris"],
    [5, "Quel club Arsène Wenger a-t-il entraîné juste avant Arsenal ?", "Nagoya Grampus", "AS Monaco", "AS Nancy-Lorraine", "Strasbourg"],
    [5, "À quelle distance de la ligne de but se trouve le point de penalty ?", "11 m", "9,15 m", "12 m", "16,5 m"],

    [1, "Combien de mi-temps compte un match de football ?", "2", "3", "4", "1"],
    [1, "Quelle partie du corps les joueurs de champ n'ont-ils pas le droit d'utiliser ?", "Les mains et les bras", "La tête", "La poitrine", "Les cuisses"],
    [1, "Quel pays a remporté la Coupe du monde 1998 ?", "France", "Brésil", "Italie", "Allemagne"],
    [1, "Comment s'appelle le championnat de France de première division ?", "Ligue 1", "Premier League", "Liga", "Serie A"],
    [1, "Comment s'appelle le championnat d'Angleterre ?", "Premier League", "Bundesliga", "Liga", "Eredivisie"],
    [1, "Combien de points rapporte une victoire en championnat ?", "3", "2", "1", "4"],
    [1, "Une faute d'un défenseur dans sa propre surface de réparation donne le plus souvent…", "Un penalty", "Un corner", "Une rentrée de touche", "Une remise en jeu aux 6 mètres"],
    [1, "Quel club joue au Camp Nou ?", "FC Barcelone", "Real Madrid", "Atlético Madrid", "Valence"],
    [1, "Dans quel pays se joue la Bundesliga ?", "Allemagne", "Autriche", "Suisse", "Pays-Bas"],
    [1, "Quel club Kylian Mbappé a-t-il rejoint en 2024 ?", "Real Madrid", "Liverpool", "FC Barcelone", "Manchester City"],
    [2, "Quel attaquant norvégien est la star de Manchester City ?", "Erling Haaland", "Martin Ødegaard", "Alexander Sørloth", "Ole Gunnar Solskjær"],
    [2, "Qui gardait les buts de la France championne du monde 1998 ?", "Fabien Barthez", "Bernard Lama", "Lionel Charbonnier", "Grégory Coupet"],
    [2, "Quel pays a battu la France en finale de la Coupe du monde 2006 ?", "Italie", "Brésil", "Portugal", "Allemagne"],
    [2, "Quel club joue à Old Trafford ?", "Manchester United", "Manchester City", "Liverpool", "Everton"],
    [2, "Dans quel club espagnol Antoine Griezmann a-t-il joué la majeure partie de sa carrière ?", "Atlético Madrid", "Real Sociedad", "FC Barcelone", "Real Madrid"],
    [2, "Quel club a remporté la Ligue des champions 2024 ?", "Real Madrid", "Borussia Dortmund", "Bayern Munich", "Manchester City"],
    [2, "Qui était le capitaine de l'équipe de France championne du monde en 2018 ?", "Hugo Lloris", "Raphaël Varane", "Paul Pogba", "Antoine Griezmann"],
    [2, "Quel club Jürgen Klopp a-t-il entraîné de 2015 à 2024 ?", "Liverpool", "Borussia Dortmund", "Bayern Munich", "Chelsea"],
    [2, "Quel pays a remporté la Coupe du monde 2014 ?", "Allemagne", "Argentine", "Brésil", "Pays-Bas"],
    [2, "Avec quel club anglais Didier Drogba est-il devenu une légende ?", "Chelsea", "Arsenal", "Tottenham", "Manchester United"],
    [3, "Comment l'Italie a-t-elle battu la France en finale de la Coupe du monde 2006 ?", "Aux tirs au but", "Par un but en or", "2-0 dans le temps réglementaire", "En prolongation, 2-1"],
    [3, "Quel club est surnommé « les Blaugrana » ?", "FC Barcelone", "Real Madrid", "FC Séville", "Villarreal"],
    [3, "Quel club a remporté la Ligue des champions 2023 ?", "Manchester City", "Inter Milan", "Real Madrid", "Chelsea"],
    [3, "Qui était le capitaine de l'équipe de France championne du monde en 1998 ?", "Didier Deschamps", "Laurent Blanc", "Marcel Desailly", "Zinédine Zidane"],
    [3, "Quel défenseur a marqué deux buts contre la Croatie en demi-finale de la Coupe du monde 1998 ?", "Lilian Thuram", "Marcel Desailly", "Laurent Blanc", "Bixente Lizarazu"],
    [3, "Qui était le sélectionneur de la France championne du monde 1998 ?", "Aimé Jacquet", "Roger Lemerre", "Michel Hidalgo", "Gérard Houllier"],
    [3, "Quel club a été champion de France 2020-2021, devant le PSG ?", "Lille OSC", "AS Monaco", "Olympique lyonnais", "Stade rennais"],
    [3, "Quel club a été champion de France 2016-2017, devant le PSG ?", "AS Monaco", "OGC Nice", "Olympique lyonnais", "Lille OSC"],
    [3, "Quelle sélection a enchaîné Euro 2008, Coupe du monde 2010 et Euro 2012 ?", "Espagne", "Allemagne", "Italie", "Pays-Bas"],
    [3, "Quel entraîneur a dirigé Manchester United pendant 26 ans ?", "Alex Ferguson", "Arsène Wenger", "Matt Busby", "José Mourinho"],
    [3, "Quel joueur a remporté le Ballon d'or 2024 ?", "Rodri", "Vinícius Júnior", "Jude Bellingham", "Kylian Mbappé"],
    [3, "Qui a remporté le Ballon d'or 2023 ?", "Lionel Messi", "Erling Haaland", "Kylian Mbappé", "Kevin De Bruyne"],
    [3, "Quel pays a remporté l'Euro 2020 (joué en 2021) ?", "Italie", "Angleterre", "Espagne", "Danemark"],
    [3, "Quel stade a accueilli la finale de la Coupe du monde 1998 ?", "Stade de France", "Parc des Princes", "Stade Vélodrome", "Stade de Gerland"],
    [3, "Dans quel club allemand Franck Ribéry a-t-il brillé pendant 12 saisons ?", "Bayern Munich", "Borussia Dortmund", "Schalke 04", "Bayer Leverkusen"],
    [4, "Quel club a été champion de France 2011-2012, à la surprise générale ?", "Montpellier HSC", "Lille OSC", "Girondins de Bordeaux", "AS Saint-Étienne"],
    [4, "En quelle année le PSG a-t-il été racheté par Qatar Sports Investments ?", "2011", "2008", "2013", "2015"],
    [4, "Quel Brésilien a marqué un coup franc à l'effet incroyable contre la France en 1997 ?", "Roberto Carlos", "Ronaldo", "Rivaldo", "Juninho"],
    [4, "Quel club a remporté la Ligue des champions 2012 aux tirs au but, chez le Bayern Munich ?", "Chelsea", "Real Madrid", "Borussia Dortmund", "Inter Milan"],
    [4, "Qui a marqué le but du Portugal en finale de l'Euro 2016 contre la France ?", "Éder", "Cristiano Ronaldo", "Nani", "Ricardo Quaresma"],
    [4, "Qui a marqué le but de la victoire de l'Espagne en finale de l'Euro 2008 ?", "Fernando Torres", "David Villa", "Xavi", "Cesc Fàbregas"],
    [4, "Qui a remporté le Ballon d'or 2007 ?", "Kaká", "Cristiano Ronaldo", "Lionel Messi", "Didier Drogba"],
    [4, "Qui a remporté le Ballon d'or 2005 ?", "Ronaldinho", "Frank Lampard", "Steven Gerrard", "Thierry Henry"],
    [4, "Qui a marqué le troisième but de la France en finale de la Coupe du monde 1998 ?", "Emmanuel Petit", "Zinédine Zidane", "Christophe Dugarry", "Youri Djorkaeff"],
    [4, "Quel joueur allemand était surnommé « le Kaiser » ?", "Franz Beckenbauer", "Gerd Müller", "Lothar Matthäus", "Karl-Heinz Rummenigge"],
    [4, "Quel pays a remporté la Copa América 2024 ?", "Argentine", "Colombie", "Uruguay", "Brésil"],
    [4, "Quel club a remporté la première édition de la Ligue des champions sous ce nom, en 1993 ?", "Olympique de Marseille", "AC Milan", "FC Barcelone", "Manchester United"],
    [4, "Combien de buts Erling Haaland a-t-il marqués lors de sa première saison de Premier League (record) ?", "36", "32", "34", "40"],
    [5, "Contre quel club Zidane a-t-il marqué sa célèbre volée en finale de la Ligue des champions 2002 ?", "Bayer Leverkusen", "Valence", "Juventus", "Monaco"],
    [5, "Qui a remporté le Ballon d'or 2001 ?", "Michael Owen", "Raúl", "Oliver Kahn", "David Beckham"],
    [5, "Combien de buts Lionel Messi a-t-il marqués sur l'année civile 2012 (record) ?", "91", "73", "86", "100"],
    [5, "Quel pays a organisé la Coupe du monde 1938 ?", "France", "Italie", "Suisse", "Uruguay"],
    [5, "Qui était le sélectionneur de la France championne d'Europe 1984 ?", "Michel Hidalgo", "Henri Michel", "Michel Platini", "Aimé Jacquet"],
    [5, "Qui était le sélectionneur de la France championne d'Europe 2000 ?", "Roger Lemerre", "Aimé Jacquet", "Jacques Santini", "Raymond Domenech"],
    [5, "Quel attaquant allemand était surnommé « Der Bomber » ?", "Gerd Müller", "Rudi Völler", "Jürgen Klinsmann", "Uwe Seeler"],
    [5, "Quel club Raymond Kopa a-t-il quitté pour rejoindre le Real Madrid en 1956 ?", "Stade de Reims", "Racing Club de Paris", "OGC Nice", "Angers SCO"],
    [5, "En quelle année la Division 1 a-t-elle été renommée Ligue 1 ?", "2002", "1998", "2000", "2005"],
  ],

  tennis: [
    [1, "Combien y a-t-il de tournois du Grand Chelem par an ?", "4", "3", "5", "6"],
    [1, "Sur quelle surface se joue Roland-Garros ?", "Terre battue", "Gazon", "Dur", "Moquette"],
    [1, "Sur quelle surface se joue Wimbledon ?", "Gazon", "Terre battue", "Dur", "Synthétique"],
    [1, "Dans quelle ville se joue Roland-Garros ?", "Paris", "Lyon", "Marseille", "Nice"],
    [1, "Au tennis, après 15, le score passe à…", "30", "20", "25", "40"],
    [1, "De quel pays est Rafael Nadal ?", "Espagne", "Argentine", "Italie", "Portugal"],
    [2, "Quel joueur a gagné le plus de fois Roland-Garros ?", "Rafael Nadal", "Novak Djokovic", "Björn Borg", "Roger Federer"],
    [2, "Quelle couleur de tenue est obligatoire à Wimbledon ?", "Blanc", "Vert", "Libre", "Bleu marine"],
    [2, "Dans quelle ville se joue l'Open d'Australie ?", "Melbourne", "Sydney", "Brisbane", "Perth"],
    [2, "Qu'est-ce qu'un « ace » ?", "Un service gagnant que l'adversaire ne touche pas", "Une double faute", "Un smash gagnant", "Un point gagné au filet"],
    [2, "De quel pays est Roger Federer ?", "Suisse", "Autriche", "Allemagne", "Suède"],
    [2, "De quel pays est Jannik Sinner ?", "Italie", "Autriche", "Suisse", "Allemagne"],
    [2, "À combien de jeux partout joue-t-on un tie-break dans un set classique ?", "6-6", "5-5", "7-7", "4-4"],
    [3, "Qui est le dernier Français vainqueur d'un Grand Chelem en simple messieurs ?", "Yannick Noah", "Henri Leconte", "Jo-Wilfried Tsonga", "Guy Forget"],
    [3, "Quelle Française a remporté Wimbledon en 2013 ?", "Marion Bartoli", "Amélie Mauresmo", "Caroline Garcia", "Mary Pierce"],
    [3, "Comment s'appelle le court central de Roland-Garros ?", "Court Philippe-Chatrier", "Court Suzanne-Lenglen", "Court Simonne-Mathieu", "Court Yannick-Noah"],
    [3, "Quelle joueuse a remporté 23 titres du Grand Chelem dans l'ère Open ?", "Serena Williams", "Steffi Graf", "Martina Navrátilová", "Venus Williams"],
    [3, "Quel homme détenait le record de titres du Grand Chelem fin 2025 ?", "Novak Djokovic", "Rafael Nadal", "Roger Federer", "Pete Sampras"],
    [3, "Quel joueur a remporté Roland-Garros en 2024 et 2025 ?", "Carlos Alcaraz", "Jannik Sinner", "Alexander Zverev", "Casper Ruud"],
    [3, "Qui a remporté Wimbledon 2025 chez les hommes ?", "Jannik Sinner", "Carlos Alcaraz", "Novak Djokovic", "Taylor Fritz"],
    [3, "Quel ancien joueur a donné son nom à une marque au crocodile ?", "René Lacoste", "Fred Perry", "Henri Cochet", "Jean Borotra"],
    [3, "Quel homme avait gagné le plus de fois Wimbledon fin 2025 ?", "Roger Federer", "Novak Djokovic", "Pete Sampras", "Björn Borg"],
    [4, "Quels Grands Chelems Amélie Mauresmo a-t-elle gagnés en 2006 ?", "Open d'Australie et Wimbledon", "Roland-Garros et US Open", "Wimbledon et US Open", "Open d'Australie et Roland-Garros"],
    [4, "Qui a affronté John Isner lors du plus long match de l'histoire (Wimbledon 2010) ?", "Nicolas Mahut", "Gilles Simon", "Richard Gasquet", "Gaël Monfils"],
    [4, "Quel est le dernier homme à avoir réussi le Grand Chelem sur une même année ?", "Rod Laver", "Novak Djokovic", "Björn Borg", "Roy Emerson"],
    [4, "Quelle joueuse a réussi le « Golden Slam » (4 Grands Chelems + JO) en 1988 ?", "Steffi Graf", "Martina Navrátilová", "Monica Seles", "Chris Evert"],
    [4, "Lequel faisait partie des « Quatre Mousquetaires » du tennis français ?", "Jean Borotra", "Yannick Noah", "Henri Leconte", "Guy Forget"],
    [4, "Dans quelle ville se jouent les finales ATP de fin d'année depuis 2021 ?", "Turin", "Londres", "Paris", "Shanghai"],
    [4, "En quelle année Yannick Noah a-t-il gagné Roland-Garros ?", "1983", "1981", "1985", "1987"],
    [5, "Quelle joueuse détient le record absolu de 24 titres du Grand Chelem ?", "Margaret Court", "Serena Williams", "Steffi Graf", "Billie Jean King"],
    [5, "Contre quel pays la France a-t-elle remporté la Coupe Davis 2017 ?", "Belgique", "Croatie", "Suisse", "Argentine"],
    [5, "Quelle est la hauteur du filet en son centre ?", "0,914 m", "1,07 m", "0,80 m", "1 m"],
    [5, "Combien de titres à Roland-Garros Rafael Nadal a-t-il remportés ?", "14", "12", "13", "15"],
    [5, "Quelle Française a remporté Roland-Garros en 2000 ?", "Mary Pierce", "Amélie Mauresmo", "Nathalie Tauziat", "Julie Halard"],

    [1, "Comment appelle-t-on deux fautes de suite au service ?", "Une double faute", "Un let", "Un ace", "Un break"],
    [1, "Comment appelle-t-on le score 40-40 ?", "Égalité", "Avantage", "Balle de match", "Tie-break"],
    [1, "Dans quelle ville se joue l'US Open ?", "New York", "Los Angeles", "Miami", "Chicago"],
    [1, "De quel pays est Novak Djokovic ?", "Serbie", "Croatie", "Russie", "Bosnie"],
    [1, "Combien de jeux faut-il gagner (au minimum) pour remporter un set ?", "6", "4", "5", "10"],
    [2, "Au meilleur de combien de sets se joue un match masculin de Grand Chelem ?", "5", "3", "4", "7"],
    [2, "Quel tournoi du Grand Chelem se joue en premier dans l'année ?", "Open d'Australie", "Roland-Garros", "Wimbledon", "US Open"],
    [2, "Sur quelle surface se joue l'Open d'Australie ?", "Dur", "Gazon", "Terre battue", "Moquette"],
    [2, "De quel pays est Andy Murray ?", "Royaume-Uni", "Irlande", "Australie", "Canada"],
    [2, "Quel joueur français est surnommé « La Monf » ?", "Gaël Monfils", "Richard Gasquet", "Gilles Simon", "Ugo Humbert"],
    [3, "Lequel de ces joueurs ne fait pas partie du « Big Three » ?", "Andy Murray", "Roger Federer", "Rafael Nadal", "Novak Djokovic"],
    [3, "Quelle joueuse polonaise a gagné Roland-Garros en 2020, 2022, 2023 et 2024 ?", "Iga Świątek", "Agnieszka Radwańska", "Magda Linette", "Aryna Sabalenka"],
    [3, "Qui a remporté le tournoi olympique de tennis 2024 en simple messieurs ?", "Novak Djokovic", "Carlos Alcaraz", "Jannik Sinner", "Alexander Zverev"],
    [3, "Où se sont jouées les épreuves de tennis des JO de Paris 2024 ?", "À Roland-Garros", "À Bercy", "Au Stade de France", "À Versailles"],
    [3, "Comment s'appelle le système vidéo qui juge si une balle est dehors ?", "Hawk-Eye (l'Œil de faucon)", "La VAR", "Le TMO", "Le photo-finish"],
    [3, "Comment gagne-t-on un tie-break classique ?", "Premier à 7 points avec 2 points d'écart", "Premier à 10 points", "Premier à 6 points", "Premier à 7 points, sans écart"],
    [3, "Dans quelle salle parisienne se jouait le Masters 1000 de Paris jusqu'en 2024 ?", "Bercy", "Le Zénith", "La Défense Arena", "Le Palais des Sports"],
    [4, "Quelle joueuse a remporté Roland-Garros 2025 ?", "Coco Gauff", "Aryna Sabalenka", "Iga Świątek", "Jasmine Paolini"],
    [4, "Quelle joueuse a remporté Wimbledon 2025, en gagnant la finale 6-0 6-0 ?", "Iga Świątek", "Amanda Anisimova", "Aryna Sabalenka", "Elena Rybakina"],
    [4, "Comment s'appelle la compétition féminine par nations (ex-Fed Cup) ?", "Billie Jean King Cup", "Hopman Cup", "Serena Cup", "Laver Cup"],
    [4, "Quelle Française des années 1920 a donné son nom au deuxième court de Roland-Garros ?", "Suzanne Lenglen", "Simonne Mathieu", "Françoise Dürr", "Marion Bartoli"],
    [4, "Quelle finale de Grand Chelem Jo-Wilfried Tsonga a-t-il disputée en 2008 ?", "Open d'Australie", "Roland-Garros", "Wimbledon", "US Open"],
    [4, "Combien de titres du Grand Chelem Roger Federer a-t-il gagnés ?", "20", "18", "22", "24"],
    [4, "Dans quelle ville de Majorque est né Rafael Nadal ?", "Manacor", "Palma", "Ibiza", "Valence"],
    [4, "Comment s'appelle le court central de l'US Open ?", "Arthur Ashe Stadium", "Rod Laver Arena", "Billie Jean King Arena", "Louis Armstrong Court"],
    [5, "Combien de titres du Grand Chelem Pete Sampras a-t-il gagnés ?", "14", "12", "16", "11"],
    [5, "Combien de Wimbledon consécutifs Björn Borg a-t-il remportés (1976-1980) ?", "5", "4", "3", "6"],
    [5, "Quel tournoi du Grand Chelem est surnommé le « Happy Slam » ?", "Open d'Australie", "US Open", "Wimbledon", "Roland-Garros"],
  ],

  rugby: [
    [1, "Combien de joueurs par équipe au rugby à XV ?", "15", "13", "11", "12"],
    [1, "Combien de points vaut un essai ?", "5", "3", "4", "7"],
    [1, "Quelle forme a un ballon de rugby ?", "Ovale", "Ronde", "Carrée", "Plate"],
    [1, "Comment s'appelle l'équipe nationale de Nouvelle-Zélande ?", "Les All Blacks", "Les Wallabies", "Les Springboks", "Les Pumas"],
    [1, "Comment s'appelle la danse traditionnelle des All Blacks ?", "Le haka", "La samba", "Le sirtaki", "Le kapa"],
    [1, "Quel tournoi oppose chaque année la France, l'Angleterre, l'Irlande, l'Écosse, le pays de Galles et l'Italie ?", "Le Tournoi des Six Nations", "Le Rugby Championship", "La Champions Cup", "Le Top 14"],
    [2, "Combien de points vaut une transformation ?", "2", "1", "3", "5"],
    [2, "Quel pays a accueilli la Coupe du monde 2023 ?", "France", "Japon", "Angleterre", "Australie"],
    [2, "Quel pays a remporté la Coupe du monde 2023 ?", "Afrique du Sud", "Nouvelle-Zélande", "France", "Irlande"],
    [2, "À quel poste joue Antoine Dupont ?", "Demi de mêlée", "Ouvreur", "Arrière", "Troisième ligne"],
    [2, "Quel club a remporté le plus de titres de champion de France ?", "Stade toulousain", "Stade français", "ASM Clermont", "RC Toulon"],
    [2, "Quelle équipe nationale est surnommée « les Springboks » ?", "Afrique du Sud", "Australie", "Argentine", "Fidji"],
    [2, "Quelle équipe nationale est surnommée « les Wallabies » ?", "Australie", "Nouvelle-Zélande", "Samoa", "Tonga"],
    [2, "Combien de joueurs par équipe au rugby à XIII ?", "13", "15", "11", "7"],
    [2, "De quel pays était Jonah Lomu ?", "Nouvelle-Zélande", "Australie", "Fidji", "Samoa"],
    [3, "Combien de Coupes du monde l'Afrique du Sud a-t-elle gagnées jusqu'en 2023 inclus ?", "4", "3", "2", "5"],
    [3, "Quel pays a remporté la première Coupe du monde, en 1987 ?", "Nouvelle-Zélande", "Australie", "France", "Afrique du Sud"],
    [3, "Comment s'appelle le trophée de la Coupe du monde de rugby ?", "Coupe Webb-Ellis", "Bouclier de Brennus", "Trophée Calcutta", "Coupe Bledisloe"],
    [3, "Quel pays a rejoint le Tournoi en 2000 pour en faire les Six Nations ?", "Italie", "Écosse", "Irlande", "Géorgie"],
    [3, "Comment s'appelle le trophée du champion de France ?", "Bouclier de Brennus", "Coupe Webb-Ellis", "Coupe Yves-du-Manoir", "Challenge de l'Espérance"],
    [3, "Quel match est surnommé « le Crunch » ?", "France – Angleterre", "France – Irlande", "Angleterre – Écosse", "Nouvelle-Zélande – Australie"],
    [3, "Combien de joueurs par équipe forment une mêlée ?", "8", "6", "7", "5"],
    [3, "Qui était le sélectionneur du XV de France lors de la Coupe du monde 2023 ?", "Fabien Galthié", "Bernard Laporte", "Philippe Saint-André", "Guy Novès"],
    [3, "Combien de temps dure une exclusion temporaire (carton jaune) ?", "10 minutes", "5 minutes", "15 minutes", "20 minutes"],
    [3, "Quelle sélection est surnommée « le XV de la Rose » ?", "Angleterre", "Pays de Galles", "Écosse", "Irlande"],
    [3, "Dans quelle ville se trouve le Stade de France ?", "Saint-Denis", "Paris", "Nanterre", "Boulogne-Billancourt"],
    [4, "Quel a été le score de la finale de la Coupe du monde 2011 Nouvelle-Zélande – France ?", "8-7", "15-9", "12-11", "20-18"],
    [4, "Contre quel pays Jonny Wilkinson a-t-il passé le drop de la victoire en finale 2003 ?", "Australie", "France", "Nouvelle-Zélande", "Afrique du Sud"],
    [4, "Quel est le seul pays de l'hémisphère nord à avoir gagné la Coupe du monde ?", "Angleterre", "France", "Irlande", "Pays de Galles"],
    [4, "Quel club a remporté le plus de Coupes d'Europe (Champions Cup) ?", "Stade toulousain", "Leinster", "Saracens", "RC Toulon"],
    [4, "Quel club a remporté la Champions Cup 2025 ?", "Union Bordeaux-Bègles", "Stade toulousain", "Leinster", "Northampton"],
    [4, "Quelle sélection est surnommée « le XV du Poireau » ?", "Pays de Galles", "Irlande", "Écosse", "Italie"],
    [4, "Combien dure une mi-temps au rugby à VII ?", "7 minutes", "10 minutes", "15 minutes", "20 minutes"],
    [4, "En quelle année parmi celles-ci la France a-t-elle réalisé le Grand Chelem dans le Tournoi ?", "2022", "2019", "2015", "2017"],
    [5, "Combien de points vaut un essai de pénalité ?", "7", "5", "6", "8"],
    [5, "Selon la légende, dans quelle ville William Webb Ellis aurait-il inventé le rugby ?", "Rugby", "Londres", "Oxford", "Cambridge"],
    [5, "À quel poste jouait Fabien Galthié ?", "Demi de mêlée", "Ouvreur", "Talonneur", "Centre"],
    [5, "Quel score la France a-t-elle infligé à la Nouvelle-Zélande en demi-finale de la Coupe du monde 1999 ?", "43-31", "30-20", "24-23", "20-18"],
    [5, "Combien de titres de champion de France le Stade toulousain a-t-il remportés à l'issue de la saison 2024 ?", "23", "21", "19", "25"],

    [1, "Dans quelle direction doit-on faire une passe à la main au rugby ?", "Vers l'arrière", "Vers l'avant", "Sur le côté uniquement", "Dans n'importe quel sens"],
    [1, "Combien de points vaut une pénalité réussie ?", "3", "2", "5", "1"],
    [1, "Comment s'appelle le championnat de France de rugby ?", "Le Top 14", "La Ligue 1", "La Pro A", "Le Super Rugby"],
    [1, "Quel demi de mêlée de Toulouse est souvent considéré comme le meilleur joueur du monde ?", "Antoine Dupont", "Romain Ntamack", "Thomas Ramos", "Grégory Alldritt"],
    [2, "Combien de points vaut un drop ?", "3", "2", "1", "5"],
    [2, "Quel animal est l'emblème du XV de France ?", "Le coq", "Le lion", "L'aigle", "Le loup"],
    [2, "Que siffle l'arbitre après un en-avant ?", "Une mêlée", "Une pénalité", "Une touche", "Un essai de pénalité"],
    [2, "Avec quelle équipe Antoine Dupont a-t-il été champion olympique en 2024 ?", "France à VII", "France à XV", "Stade toulousain", "France à XIII"],
    [3, "Quel pays a remporté la Coupe du monde 1995, à domicile ?", "Afrique du Sud", "Nouvelle-Zélande", "Angleterre", "Australie"],
    [3, "Quel président a remis la Coupe du monde 1995 au capitaine sud-africain ?", "Nelson Mandela", "Frederik de Klerk", "Thabo Mbeki", "Jacob Zuma"],
    [3, "Quel pays a remporté la Coupe du monde 2015 ?", "Nouvelle-Zélande", "Australie", "Afrique du Sud", "Angleterre"],
    [3, "Quel pays a remporté la Coupe du monde 2019 ?", "Afrique du Sud", "Angleterre", "Nouvelle-Zélande", "Pays de Galles"],
    [3, "Dans quel pays se trouve le stade de Twickenham ?", "Angleterre", "Écosse", "Irlande", "Pays de Galles"],
    [3, "Comment appelle-t-on la « récompense » du dernier du Tournoi des Six Nations ?", "La cuillère de bois", "La lanterne rouge", "Le bonnet d'âne", "La fourchette d'or"],
    [3, "Quel club joue au stade Mayol ?", "RC Toulon", "Stade rochelais", "Montpellier", "Aviron bayonnais"],
    [3, "Quel pays organise la Coupe du monde 2027 ?", "Australie", "Afrique du Sud", "Angleterre", "Japon"],
    [3, "Combien de nations disputent le Rugby Championship ?", "4", "3", "5", "6"],
    [4, "Quelles équipes s'affrontent pour la Calcutta Cup ?", "Angleterre et Écosse", "France et Italie", "Irlande et Pays de Galles", "Australie et Nouvelle-Zélande"],
    [4, "Dans quelle ville se trouve le Principality Stadium (ex-Millennium Stadium) ?", "Cardiff", "Édimbourg", "Dublin", "Swansea"],
    [4, "Quel était le surnom de Sébastien Chabal ?", "L'Homme des cavernes", "Le Pitbull", "Le Bulldozer", "Le Viking"],
    [4, "Quel club joue au stade Marcel-Michelin ?", "ASM Clermont Auvergne", "CA Brive", "Stade rochelais", "Section paloise"],
    [4, "Quel club joue au stade Ernest-Wallon ?", "Stade toulousain", "Castres olympique", "USA Perpignan", "Union Bordeaux-Bègles"],
    [4, "Quel club parisien est célèbre pour ses maillots roses ?", "Stade français", "Racing 92", "Paris Université Club", "Massy"],
    [5, "Combien de joueurs figurent sur une feuille de match de rugby à XV (titulaires + remplaçants) ?", "23", "22", "25", "20"],
    [5, "En quelle année Antoine Dupont a-t-il été élu meilleur joueur du monde World Rugby pour la première fois ?", "2021", "2019", "2022", "2023"],
    [5, "Combien d'équipes participent à la Coupe du monde 2027 ?", "24", "20", "16", "32"],
    [5, "Comment s'appelle le haka le plus célèbre des All Blacks ?", "Ka Mate", "Kapa o Pango", "Haka Nui", "Te Rauparaha"],
    [5, "Jusqu'en quelle année le rugby à XV a-t-il été au programme des Jeux olympiques ?", "1924", "1936", "1908", "1948"],
    [5, "Quel pays a remporté le dernier tournoi olympique de rugby à XV, en 1924 ?", "États-Unis", "France", "Roumanie", "Grande-Bretagne"],
  ],

  f1: [
    [1, "Quelle écurie de F1 est célèbre pour ses voitures rouges ?", "Ferrari", "McLaren", "Williams", "Alpine"],
    [1, "Que signifie le drapeau à damier ?", "La fin de la course", "Un accident", "La pluie", "Un pilote disqualifié"],
    [1, "De quel pays est Max Verstappen ?", "Pays-Bas", "Belgique", "Allemagne", "Autriche"],
    [1, "De quel pays est Lewis Hamilton ?", "Royaume-Uni", "États-Unis", "Canada", "Australie"],
    [1, "Le Grand Prix de Monaco se court…", "Dans les rues de la ville", "Sur un ovale", "Sur un circuit en terre", "Sur un aéroport"],
    [1, "Pourquoi un pilote s'arrête-t-il au stand pendant la course, le plus souvent ?", "Changer de pneus", "Faire le plein", "Changer de pilote", "Se reposer"],
    [2, "Combien de titres de champion du monde Lewis Hamilton avait-il fin 2025 ?", "7", "6", "5", "8"],
    [2, "Que signifie un drapeau jaune ?", "Danger, interdiction de dépasser", "Fin de course", "Laisser passer un pilote plus rapide", "Piste glissante uniquement"],
    [2, "Dans quel pays se trouve le circuit de Spa-Francorchamps ?", "Belgique", "France", "Allemagne", "Pays-Bas"],
    [2, "Dans quel pays se trouve le circuit de Monza ?", "Italie", "Espagne", "Monaco", "Autriche"],
    [2, "De quel pays était Ayrton Senna ?", "Brésil", "Argentine", "Portugal", "Espagne"],
    [2, "Que veut dire « SC » sur les écrans de F1 ?", "Safety car", "Super course", "Stop chrono", "Sortie de circuit"],
    [2, "Quelle écurie Lewis Hamilton a-t-il rejointe en 2025 ?", "Ferrari", "Red Bull", "McLaren", "Aston Martin"],
    [3, "Qui est le seul Français champion du monde de F1 ?", "Alain Prost", "Jean Alesi", "Pierre Gasly", "René Arnoux"],
    [3, "Que signifie le drapeau bleu ?", "Laisser passer un pilote plus rapide", "Fin de course", "Pluie sur la piste", "Arrêt au stand obligatoire"],
    [3, "Combien de titres Max Verstappen a-t-il gagnés de suite entre 2021 et 2024 ?", "4", "3", "2", "5"],
    [3, "Qui a été sacré champion du monde de F1 en 2025 ?", "Lando Norris", "Max Verstappen", "Oscar Piastri", "Charles Leclerc"],
    [3, "Combien de points rapporte une victoire en Grand Prix ?", "25", "10", "20", "30"],
    [3, "À quoi sert le DRS ?", "Ouvrir l'aileron arrière pour faciliter les dépassements", "Refroidir les freins", "Changer la pression des pneus", "Communiquer avec le stand"],
    [3, "Quelle écurie a remporté le plus de titres constructeurs ?", "Ferrari", "McLaren", "Williams", "Mercedes"],
    [3, "Sous quel nom l'écurie du groupe Renault court-elle en F1 ?", "Alpine", "Ligier", "Peugeot", "Matra"],
    [4, "Combien de titres de champion du monde Alain Prost a-t-il remportés ?", "4", "3", "2", "5"],
    [4, "Lors de quel Grand Prix Ayrton Senna s'est-il tué en 1994 ?", "Saint-Marin (Imola)", "Monaco", "Brésil", "Belgique"],
    [4, "En quelle année a eu lieu le premier championnat du monde de F1 ?", "1950", "1946", "1955", "1960"],
    [4, "Qui est le plus jeune vainqueur d'un Grand Prix (Espagne 2016) ?", "Max Verstappen", "Sebastian Vettel", "Charles Leclerc", "Lando Norris"],
    [4, "Combien de titres Michael Schumacher a-t-il gagnés avec Ferrari ?", "5", "7", "4", "6"],
    [4, "Où Pierre Gasly a-t-il remporté son premier Grand Prix en 2020 ?", "Monza", "Monaco", "Spa", "Silverstone"],
    [4, "En quel mois se court traditionnellement le Grand Prix de Monaco ?", "Mai", "Juillet", "Avril", "Septembre"],
    [5, "Qui a été le premier champion du monde de F1, en 1950 ?", "Giuseppe Farina", "Juan Manuel Fangio", "Alberto Ascari", "Stirling Moss"],
    [5, "Combien de titres de champion du monde Juan Manuel Fangio a-t-il remportés ?", "5", "4", "3", "6"],
    [5, "En quelle année le « halo » (protection de la tête) est-il devenu obligatoire ?", "2018", "2016", "2020", "2014"],
    [5, "En quelle année Romain Grosjean a-t-il survécu à son accident enflammé à Bahreïn ?", "2020", "2019", "2021", "2018"],
    [5, "Dans quelle commune se trouve le circuit Paul-Ricard ?", "Le Castellet", "Magny-Cours", "Nogaro", "Le Mans"],
    [5, "Quelle couleur ont les pneus pluie (full wet) Pirelli ?", "Bleu", "Vert", "Blanc", "Jaune"],

    [1, "Combien de voitures chaque écurie aligne-t-elle en course ?", "2", "1", "3", "4"],
    [1, "Comment appelle-t-on la première place sur la grille de départ ?", "La pole position", "La tête de série", "Le pôle Nord", "La première ligne"],
    [1, "De quel pays est Charles Leclerc ?", "Monaco", "France", "Italie", "Suisse"],
    [1, "Quelle écurie est surnommée « la Scuderia » ?", "Ferrari", "McLaren", "Red Bull", "Aston Martin"],
    [2, "Que signifie le drapeau rouge ?", "La course est interrompue", "Un pilote est disqualifié", "Dernier tour", "Danger, ralentir"],
    [2, "Quel pilote espagnol a été champion du monde en 2005 et 2006 ?", "Fernando Alonso", "Carlos Sainz", "Pedro de la Rosa", "Jaime Alguersuari"],
    [2, "Combien de titres de champion du monde Michael Schumacher a-t-il remportés ?", "7", "5", "6", "4"],
    [2, "De quel pays est Oscar Piastri ?", "Australie", "Nouvelle-Zélande", "Royaume-Uni", "Afrique du Sud"],
    [2, "Sur quel circuit se court le Grand Prix de Grande-Bretagne ?", "Silverstone", "Brands Hatch", "Donington", "Goodwood"],
    [2, "Quelle écurie a remporté tous les titres constructeurs de 2014 à 2021 ?", "Mercedes", "Red Bull", "Ferrari", "McLaren"],
    [3, "Avec quelle écurie Fernando Alonso a-t-il été champion du monde ?", "Renault", "Ferrari", "McLaren", "Minardi"],
    [3, "Combien de titres de champion du monde Sebastian Vettel a-t-il remportés ?", "4", "3", "2", "5"],
    [3, "Dans quelle écurie Ayrton Senna et Alain Prost étaient-ils coéquipiers ?", "McLaren", "Williams", "Ferrari", "Lotus"],
    [3, "Quel pilote détient le record de victoires en Grand Prix ?", "Lewis Hamilton", "Michael Schumacher", "Max Verstappen", "Sebastian Vettel"],
    [3, "Quel pilote finlandais était surnommé « Iceman » ?", "Kimi Räikkönen", "Mika Häkkinen", "Valtteri Bottas", "Keke Rosberg"],
    [3, "Quelle écurie américaine a fait ses débuts en F1 en 2026 ?", "Cadillac", "Ford", "Haas", "Andretti"],
    [3, "Comment s'appelle le tour qui précède le départ d'un Grand Prix ?", "Le tour de formation", "Le tour d'honneur", "Le tour de chauffe officiel", "Le tour lancé"],
    [4, "Quel constructeur allemand a repris l'écurie Sauber pour 2026 ?", "Audi", "BMW", "Porsche", "Volkswagen"],
    [4, "Quel circuit japonais a la particularité d'avoir un tracé en forme de 8 ?", "Suzuka", "Fuji", "Motegi", "Okayama"],
    [4, "Quel a été le premier Grand Prix de nuit de l'histoire, en 2008 ?", "Singapour", "Bahreïn", "Abou Dhabi", "Qatar"],
    [4, "Quel Français a remporté le Grand Prix de Monaco 1996 ?", "Olivier Panis", "Jean Alesi", "Alain Prost", "Romain Grosjean"],
    [4, "Quel Canadien a été champion du monde en 1997 ?", "Jacques Villeneuve", "Gilles Villeneuve", "Lance Stroll", "Nicholas Latifi"],
    [4, "Quel pilote a pris sa retraite juste après son titre de champion du monde 2016 ?", "Nico Rosberg", "Jenson Button", "Felipe Massa", "Mark Webber"],
    [4, "Que signifie la bande rouge sur un pneu de F1 ?", "Gomme tendre", "Gomme dure", "Gomme mi-dure", "Pneu pluie"],
    [5, "Combien de Grands Prix Max Verstappen a-t-il gagnés sur 22 en 2023 (record) ?", "19", "15", "17", "21"],
    [5, "Quelle est la distance minimale d'un Grand Prix (hors Monaco) ?", "Environ 305 km", "Environ 200 km", "Environ 400 km", "Environ 500 km"],
    [5, "Quelle a été la seule victoire en Grand Prix de Jean Alesi ?", "Canada 1995", "France 1995", "Monaco 1996", "Italie 1994"],
    [5, "Lors de quel Grand Prix Jules Bianchi a-t-il eu son grave accident en 2014 ?", "Japon", "Brésil", "Belgique", "Singapour"],
  ],

  velo: [
    [1, "Quelle est la couleur du maillot du leader du Tour de France ?", "Jaune", "Vert", "Rose", "Blanc"],
    [1, "En quel mois se court le Tour de France ?", "Juillet", "Mai", "Septembre", "Avril"],
    [1, "Sur quelle avenue le Tour de France se termine-t-il traditionnellement ?", "Les Champs-Élysées", "La Croisette", "La Canebière", "La promenade des Anglais"],
    [1, "Que récompense le maillot à pois ?", "Le meilleur grimpeur", "Le meilleur sprinteur", "Le meilleur jeune", "Le plus combatif"],
    [1, "Comment appelle-t-on le Tour d'Italie ?", "Le Giro", "La Vuelta", "Le Calcio", "La Corsa"],
    [2, "Que récompense le maillot vert du Tour de France ?", "Le classement par points", "Le meilleur grimpeur", "Le meilleur jeune", "Le leader au temps"],
    [2, "Quelle est la couleur du maillot de leader du Giro ?", "Rose", "Jaune", "Rouge", "Bleu"],
    [2, "De quel pays est Tadej Pogačar ?", "Slovénie", "Slovaquie", "Croatie", "Autriche"],
    [2, "De quel pays est Jonas Vingegaard ?", "Danemark", "Norvège", "Suède", "Pays-Bas"],
    [2, "Que récompense le maillot blanc du Tour de France ?", "Le meilleur jeune", "Le meilleur grimpeur", "Le plus combatif", "La meilleure équipe"],
    [2, "Quel maillot porte le champion du monde sur route ?", "Le maillot arc-en-ciel", "Le maillot doré", "Le maillot tricolore", "Le maillot à pois"],
    [2, "Comment appelle-t-on le Tour d'Espagne ?", "La Vuelta", "Le Giro", "La Liga", "La Ronda"],
    [3, "Qui est le dernier Français vainqueur du Tour de France (1985) ?", "Bernard Hinault", "Laurent Fignon", "Thibaut Pinot", "Richard Virenque"],
    [3, "Lequel de ces coureurs n'a PAS gagné 5 Tours de France ?", "Chris Froome", "Eddy Merckx", "Jacques Anquetil", "Miguel Indurain"],
    [3, "Quelle course est surnommée « l'Enfer du Nord » ?", "Paris-Roubaix", "Le Tour des Flandres", "Liège-Bastogne-Liège", "Paris-Tours"],
    [3, "Que reçoit le vainqueur de Paris-Roubaix ?", "Un pavé", "Une coupe en argent", "Un maillot jaune", "Un vélo en or"],
    [3, "Quelle montée est célèbre pour ses 21 virages numérotés ?", "L'Alpe d'Huez", "Le Tourmalet", "Le Galibier", "Le Ventoux"],
    [3, "Quel coureur était surnommé « le Cannibale » ?", "Eddy Merckx", "Bernard Hinault", "Lance Armstrong", "Fausto Coppi"],
    [3, "Quel était le surnom de Bernard Hinault ?", "Le Blaireau", "Le Cannibale", "Le Pirate", "Le Roi René"],
    [3, "Qui a réalisé le doublé Giro – Tour de France en 2024 ?", "Tadej Pogačar", "Jonas Vingegaard", "Primož Roglič", "Remco Evenepoel"],
    [3, "Comment appelle-t-on le dernier du classement général du Tour ?", "La lanterne rouge", "La voiture-balai", "Le gruppetto", "Le flahute"],
    [3, "Combien d'étapes compte habituellement le Tour de France ?", "21", "15", "25", "30"],
    [4, "Quel coureur était surnommé « l'Éternel second » ?", "Raymond Poulidor", "Laurent Fignon", "Joop Zoetemelk", "Jan Ullrich"],
    [4, "Quel est le surnom du mont Ventoux ?", "Le Géant de Provence", "Le Toit du Tour", "Le Mont Chauve des Alpes", "La Bête des Pyrénées"],
    [4, "Quelle est la couleur du maillot de leader de la Vuelta ?", "Rouge", "Or", "Orange", "Jaune"],
    [4, "En quelle année s'est couru le premier Tour de France ?", "1903", "1910", "1899", "1919"],
    [4, "Combien de titres de champion du monde Julian Alaphilippe a-t-il remportés ?", "2", "1", "3", "0"],
    [4, "Combien de Tours de France Tadej Pogačar avait-il gagnés fin 2025 ?", "4", "3", "2", "5"],
    [4, "Dans quelle ville s'est terminé le Tour de France 2024, à cause des JO de Paris ?", "Nice", "Marseille", "Lyon", "Bordeaux"],
    [4, "Combien de Tours de France ont été retirés à Lance Armstrong ?", "7", "5", "6", "4"],
    [5, "Qui a gagné le premier Tour de France, en 1903 ?", "Maurice Garin", "Henri Desgrange", "Lucien Petit-Breton", "Octave Lapize"],
    [5, "Par combien de secondes Greg LeMond a-t-il battu Laurent Fignon sur le Tour 1989 ?", "8 secondes", "18 secondes", "3 secondes", "38 secondes"],
    [5, "Combien de grandes classiques appelle-t-on « Monuments » ?", "5", "3", "4", "7"],
    [5, "Quelle classique est surnommée « la Primavera » ?", "Milan-San Remo", "Le Tour de Lombardie", "Paris-Nice", "Les Strade Bianche"],
    [5, "Combien de maillots à pois Richard Virenque a-t-il remportés sur le Tour ?", "7", "5", "6", "4"],
    [5, "Quel journal a créé le Tour de France en 1903 ?", "L'Auto", "L'Équipe", "Le Petit Journal", "Le Figaro"],

    [1, "Quelle est la course cycliste la plus célèbre du monde ?", "Le Tour de France", "Paris-Roubaix", "Le Giro", "Milan-San Remo"],
    [1, "Comment appelle-t-on le groupe principal des coureurs ?", "Le peloton", "Le troupeau", "La meute", "Le convoi"],
    [1, "Quel coureur slovène a gagné le Tour de France 2024 et 2025 ?", "Tadej Pogačar", "Primož Roglič", "Matej Mohorič", "Jan Tratnik"],
    [1, "Que fait un coureur « échappé » ?", "Il roule devant le peloton", "Il abandonne la course", "Il roule derrière le peloton", "Il change de vélo"],
    [2, "Que veut dire « CLM » en cyclisme ?", "Contre-la-montre", "Course longue montagne", "Classement lent moyen", "Col le plus monté"],
    [2, "Quel coureur danois a gagné le Tour de France en 2022 et 2023 ?", "Jonas Vingegaard", "Mads Pedersen", "Jakob Fuglsang", "Bjarne Riis"],
    [2, "De quel pays est Remco Evenepoel ?", "Belgique", "Pays-Bas", "France", "Luxembourg"],
    [2, "Comment appelle-t-on une grande course d'un seul jour comme Paris-Roubaix ?", "Une classique", "Une étape", "Un critérium", "Un prologue"],
    [3, "Quel coureur français est surnommé « Loulou » ?", "Julian Alaphilippe", "Thibaut Pinot", "Romain Bardet", "Warren Barguil"],
    [3, "Quel coureur détient le record de victoires d'étapes sur le Tour de France ?", "Mark Cavendish", "Eddy Merckx", "Bernard Hinault", "Peter Sagan"],
    [3, "Quel coureur néerlandais a remporté Paris-Roubaix en 2023, 2024 et 2025 ?", "Mathieu van der Poel", "Wout van Aert", "Dylan van Baarle", "Niki Terpstra"],
    [3, "Quel col pyrénéen est le plus souvent emprunté par le Tour ?", "Le Tourmalet", "L'Aubisque", "Le Peyresourde", "L'Aspin"],
    [4, "Quel champion français était le grand-père de Mathieu van der Poel ?", "Raymond Poulidor", "Jacques Anquetil", "Bernard Hinault", "Louison Bobet"],
    [4, "Quel « Monument » Thibaut Pinot a-t-il remporté en 2018 ?", "Le Tour de Lombardie", "Liège-Bastogne-Liège", "Milan-San Remo", "Paris-Roubaix"],
    [4, "Combien de Tours de France Laurent Fignon a-t-il gagnés ?", "2", "1", "3", "4"],
    [4, "En quelle année le Tour de France Femmes a-t-il été relancé ?", "2022", "2019", "2020", "2024"],
    [4, "Dans quelle ville italienne a eu lieu le Grand Départ du Tour de France 2024 ?", "Florence", "Turin", "Rome", "Milan"],
    [4, "Quelle Française a remporté le Tour de France Femmes 2025 ?", "Pauline Ferrand-Prévot", "Juliette Labous", "Évita Muzic", "Audrey Cordon-Ragot"],
    [4, "Combien de Giro Eddy Merckx a-t-il gagnés ?", "5", "3", "4", "6"],
    [5, "Combien d'étapes du Tour de France Mark Cavendish a-t-il gagnées ?", "35", "34", "30", "38"],
    [5, "Dans quelle ville a eu lieu le Grand Départ du Tour de France 2025 ?", "Lille", "Bilbao", "Copenhague", "Brest"],
    [5, "Dans quelle ville Tadej Pogačar est-il devenu champion du monde en 2024 ?", "Zurich", "Glasgow", "Wollongong", "Louvain"],
    [5, "Quelle classique est surnommée « la Doyenne » ?", "Liège-Bastogne-Liège", "Paris-Roubaix", "Paris-Tours", "Le Tour des Flandres"],
    [5, "Quelle classique est surnommée « la Classique des feuilles mortes » ?", "Le Tour de Lombardie", "Paris-Tours", "Milan-San Remo", "La Flèche wallonne"],
    [5, "Dans quelle ville Eddy Merckx a-t-il battu le record de l'heure en 1972 ?", "Mexico", "Milan", "Bordeaux", "Bruxelles"],
    [5, "Quelle est la couleur du maillot du meilleur grimpeur du Giro ?", "Bleu", "À pois", "Vert", "Blanc"],
  ],
};
